# Training Configuration
training:
  epochs: 50
  batch_size: 256
  learning_rate: 0.001
  weight_decay: 0.0001
  gradient_clip: 1.0

# Model Configuration
model:
  input_size: 5  # OHLCV features
  hidden_size: 128
  num_layers: 2
  num_heads: 4
  dropout: 0.1
  seq_length: 60  # Use 60 timesteps for prediction

# Data Configuration
data:
  symbol: "EURUSD=X"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  target_column: "Close"

# Fetching Configuration
fetching:
  max_retries: 5
  retry_delay: 5  # seconds
  batch_days: 365  # Fetch data in yearly batches

# Paths
paths:
  data_dir: "./data"
  models_dir: "./models"
  logs_dir: "./logs"
  data_file: "./data/eurusd.csv"
  model_file: "./models/model.pt"

# Device Configuration
device: "cuda"  # Will auto-fallback to CPU if CUDA unavailable
